[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "gcc", "python39Packages.wheel"]

[phases.install]
cmds = [
  "cd website/backend",
  "pip3 install --upgrade pip wheel setuptools",
  "pip3 install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "cd website/backend && python -m uvicorn app:app --host 0.0.0.0 --port $PORT --log-level debug"
