[phases.setup]
nixPkgs = ["python39", "python39Packages.pip"]

[phases.install]
cmds = ["cd website/backend && pip3 install -r requirements.txt"]

[start]
cmd = "cd website/backend && python -m uvicorn app:app --host 0.0.0.0 --port $PORT --log-level debug"
