services:
  - type: web
    name: book-bud-backend
    env: python
    buildCommand: pip install -r website/backend/requirements.txt && cp *.py website/backend/
    startCommand: cd website/backend && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
    healthCheckPath: /status
